name: flame1d-timing

on:
  pull_request:
  schedule:
  - cron:  '0 9 * * *'


jobs:

    flame1d:
        name: flame1d-check
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        - name: check-todays-data
          run: |
             .ci-support/check-for-latest-data.sh flame1d_lazy_logs
