name: isolator-timing

on:
  pull_request:
  schedule:
  - cron:  '0 9 * * *'


jobs:

    isolator:
        name: isolator-check
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        - name: check-todays-data
          run: |
             .ci-support/check-for-latest-data.sh isolator_logs
