name: y2-prediction-timing

on:
  pull_request:
  push:
    branches: main
  schedule:
  - cron:  '5 0 * * *'


jobs:

    y2-prediction:
        name: y2-prediction-check
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        - name: check-todays-data
          run: |
             .ci-support/check-for-latest-data.sh y2-prediction/sql

